In [20]:
import numpy as np
import joblib
import matplotlib.pyplot as plt
import pandas as pd

In [28]:
class Perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.randn(3) * 1e-4
        print(f"self.weights:{self.weights}")
        self.eta = eta
        self.epochs = epochs
        
    def activationFunction(self,inputs,weights):
        z = np.dot(inputs,weights)
        return np.where(z> 0,1,0)
    
    def fit(self,X,y):
        self.X = X
        self.y = y 
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X_with_bias:  \n{X_with_bias}")
        
        
        for epoch in range(self.epochs):
            print(f"for epoch: {epoch}")
            y_hat = self.activationFunction(X_with_bias , self.weights)
            print(f"predicted value: \n{y_hat}")
            error = self.y - y_hat
            print(f"error : \n {error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T , error)
            print(f"updated wights: \n {self.weights}")
        
    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(self.X),1))]
        return self.activationFunction(X_with_bias , self.weights)

### AND Operation

In [51]:
data = {"x1": [0,0,1,1] , "x2": [0,1,0,1] , "y" : [0,0,0,1]}

AND = pd.DataFrame(data
                  )

In [52]:
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [53]:
X = AND.drop('y',axis=1)

In [54]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [55]:
y = AND['y']
y.to_frame()

y
0  0
1  1
2  1
3  1

In [56]:
model = Perceptron(eta=0.5,epochs=10)
model.fit(X,y)

self.weights:[3.44228397e-05 9.25241529e-05 8.58477886e-05]
X_with_bias:  
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 1 0 1]
error : 
 0    0
1    0
2    1
3    0
Name: y, dtype: int64
updated wights: 
 [ 5.00034423e-01  9.25241529e-05 -4.99914152e-01]
for epoch: 1
predicted value: 
[1 1 1 1]
error : 
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated wights: 
 [5.00034423e-01 9.25241529e-05 8.58477886e-05]
for epoch: 2
predicted value: 
[0 1 1 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated wights: 
 [5.00034423e-01 9.25241529e-05 8.58477886e-05]
for epoch: 3
predicted value: 
[0 1 1 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated wights: 
 [5.00034423e-01 9.25241529e-05 8.58477886e-05]
for epoch: 4
predicted value: 
[0 1 1 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated wights: 
 [5.00034423e-01 9.25241529e-05 8.58477886e-05]
for epoch: 5
predicted value: 


In [57]:
model.predict(X)

array([0, 1, 1, 1])

In [58]:
model.weights

array([5.00034423e-01, 9.25241529e-05, 8.58477886e-05])

### OR Operation

In [61]:
data = {"x1": [0,0,1,1] , "x2": [0,1,0,1] , "y" : [0,1,1,1]}

OR = pd.DataFrame(data
                  )

In [62]:
X = OR.drop('y',axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [63]:
y = OR['y']
y.to_frame()

y
0  0
1  1
2  1
3  1

In [64]:

model = Perceptron(eta=0.5,epochs=10)
model.fit(X,y)

self.weights:[6.14960250e-05 1.75085574e-05 1.01904378e-05]
X_with_bias:  
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 1 1 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated wights: 
 [6.14960250e-05 1.75085574e-05 1.01904378e-05]
for epoch: 1
predicted value: 
[0 1 1 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated wights: 
 [6.14960250e-05 1.75085574e-05 1.01904378e-05]
for epoch: 2
predicted value: 
[0 1 1 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated wights: 
 [6.14960250e-05 1.75085574e-05 1.01904378e-05]
for epoch: 3
predicted value: 
[0 1 1 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated wights: 
 [6.14960250e-05 1.75085574e-05 1.01904378e-05]
for epoch: 4
predicted value: 
[0 1 1 1]
error : 
 0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated wights: 
 [6.14960250e-05 1.75085574e-05 1.01904378e-05]
for epoch: 5
predicted value: 
[0 

In [65]:
model.predict(X)

array([0, 1, 1, 1])

In [66]:
model.weights


array([6.14960250e-05, 1.75085574e-05, 1.01904378e-05])